name: olivia
version: '1.0'
summary: Deadass music player for Linux
description: |
  Olivia is a online/offline cloud based music player like iTunes, Spotify etc,Olivia allows you to search any music online stream it, you can set player to cache your streams while playback. Olivia lets you create and manage your music library.

grade: stable
confinement: strict

apps:
  olivia:
    command: desktop-launch olivia
    desktop: ./gui/olivia.desktop
    plugs:
        - home
        - unity7
        - browser-support
        - network
        - network-bind
        - opengl
        - pulseaudio
        - x11
        - alsa
        - desktop
        - network-manager
        - gsettings
        - process-control
parts:
   qt:
     plugin: qmake
     qt-version: qt5
     source-type: git
     source: https://github.com/keshavbhatt/olivia.git
     build-packages:
            - build-essential
            - qtbase5-dev
            - libqt5webkit5-dev
     stage:
          - -usr/share/pkgconfig
     stage-packages:
          - libqt5sql5-sqlite
          - libqt5webkit5
          - libqt5x11extras5

     after: [desktop-qt5]
 
   deps:
      plugin: nil
      stage-packages:
            - mpv
            - socat
            - youtube-dl
            - wget
            - coreutils
