name: olivia-test
version: '1.0'
summary: Elegant Cloud Music Player for Linux Desktop
description: |
  Olivia is a online/offline cloud based music player like iTunes, Spotify etc,Olivia allows you to search any music online stream it, you can set player to cache your streams while playback. Olivia lets you create and manage your music library.
grade: stable
confinement: strict
icon: snap/gui/icon.png

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  olivia:
    command: desktop-launch olivia
    desktop: snap/gui/olivia.desktop
    plugs:
        - home
        - unity7
        - browser-support
        - network
        - network-bind
        - opengl
        - pulseaudio
        - x11
        - alsa
        - desktop
        - network-manager
        - gsettings
        - process-control
parts:
   deps:
     plugin: nil
     stage-packages:
            - socat
            - python
            - wget
            - coreutils
   ppa:
     plugin: nil
     override-pull: |
       apt --yes install software-properties-common apt-utils
       add-apt-repository -yu ppa:mc3man/mpv-tests
   mpv:
     plugin: nil
     after: [ppa,qt]
     stage-packages:
           - mpv
   qt:
     plugin: qmake
     qt-version: qt5
     source-type: git
     source: https://github.com/keshavbhatt/olivia.git
     build-packages:
            - build-essential
            - qtbase5-dev
            - libqt5webkit5-dev
     stage:
          - -usr/share/pkgconfig
     override-build: |
      set -xe
      snapcraftctl build
      part_src=$SNAPCRAFT_PART_INSTALL/../src
      snap_gui=$SNAPCRAFT_STAGE/../snap/gui
      mkdir -vp $snap_gui
      cp -v $part_src/snap/gui/olivia.desktop $snap_gui
     stage-packages:
          - libqt5sql5-sqlite
          - libqt5webkit5
          - libqt5x11extras5
     after: [desktop-qt5]
